/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/schedules/{scheduleId}/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["hold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/{reservationId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{scheduleId}/seats/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{scheduleId}/seats/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["layout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{scheduleId}/queue/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/{reservationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete: operations["cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["event"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EnterResponse: {
            /** Format: int64 */
            position?: number;
        };
        HoldRequest: {
            /** Format: int64 */
            scheduleId: number;
            /** Format: int64 */
            seatId: number;
        };
        HoldResponse: {
            /** Format: int64 */
            reservationId?: number;
            /** Format: date-time */
            expiresAt?: string;
        };
        ConfirmResponse: {
            /** Format: int64 */
            reservationId?: number;
            status?: string;
            paymentTransactionId?: string;
        };
        SeatStatusResponse: {
            /** Format: int64 */
            scheduleId?: number;
            sections?: components["schemas"]["SectionStatusResponse"][];
        };
        SectionStatusResponse: {
            /** Format: int64 */
            sectionId?: number;
            /** Format: int32 */
            seatCount?: number;
            /** Format: byte */
            bitmap?: string;
        };
        SeatLayoutResponse: {
            /** Format: int64 */
            scheduleId?: number;
            sections?: components["schemas"]["SectionResponse"][];
        };
        SeatResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            rowNo?: number;
            /** Format: int32 */
            colNo?: number;
        };
        SectionResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: int32 */
            seatCount?: number;
            seats?: components["schemas"]["SeatResponse"][];
        };
        StatusResponse: {
            /** Format: int64 */
            position?: number;
            admitted?: boolean;
            token?: string;
        };
        ReservationResponse: {
            /** Format: int64 */
            reservationId?: number;
            /** Format: int64 */
            scheduleId?: number;
            /** Format: int64 */
            seatId?: number;
            status?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        EventSummaryResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            venue?: string;
            /** Format: date-time */
            openAt?: string;
        };
        EventDetailResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            venue?: string;
            /** Format: date-time */
            openAt?: string;
            schedules?: components["schemas"]["ScheduleResponse"][];
        };
        ScheduleResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            startsAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    enter: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": string;
            };
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnterResponse"];
                };
            };
        };
    };
    hold: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": string;
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HoldResponse"];
                };
            };
        };
    };
    confirm: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": string;
            };
            path: {
                reservationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConfirmResponse"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeatStatusResponse"];
                };
            };
        };
    };
    layout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeatLayoutResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": string;
            };
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": string;
            };
            path: {
                reservationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationResponse"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": string;
            };
            path: {
                reservationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventSummaryResponse"][];
                };
            };
        };
    };
    event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventDetailResponse"];
                };
            };
        };
    };
}
